[package]
name = "rust_test_01"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=['std']
foo = []
std = []
aaa = []

[workspace]
members = [
    "bin/prj-01",
]
