[package]
name = "prj-01"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "test"
path = "src/run_06.rs"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", features=["derive"]}
bytes = "1.0"
rand = "0.7.0"
futures= { version = "0.3.9", features = ["thread-pool"]}
futures-timer = "3.0.1"
tokio = "1.14.0"
chrono = "0.4.19"